version: '2'
services:
  web:
    scale: 1
    health_check:
      port: 80
      interval: 2000
      initializing_timeout: 60000
      strategy: recreate
      healthy_threshold: 1
      response_timeout: 2000